/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.7.10"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    implementation("io.vertx:vertx-core:4.3.3")
    implementation("io.vertx:vertx-mongo-client:4.3.3")

    // Logging
    implementation("ch.qos.logback:logback-core:1.2.6")
    implementation("org.slf4j:slf4j-api:1.7.30")

    // Netty for Mac M1
    //implementation("io.netty:netty-all:4.1.78.Final")
    //implementation("io.netty:netty-resolver-dns-native-macos:4.1.78.Final:osx-aarch_64")

    // JUnit 5 Dependencies
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.8.1")
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.1")
    testImplementation("io.vertx:vertx-junit5:4.3.3")

    // Use the Kotlin test library.
    testImplementation(kotlin("test"))

    // Use the Kotlin JUnit integration.
    //testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
}

application {
    // Define the main class for the application.
    mainClass.set("test.vertx.gridfs.AppKt")
}

tasks.withType<Test> {
    useJUnitPlatform()
}