/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.vertx.gridfs

import io.vertx.core.Vertx
import io.vertx.core.file.OpenOptions
import io.vertx.core.json.JsonObject
import io.vertx.ext.mongo.GridFsUploadOptions
import io.vertx.ext.mongo.MongoClient
import kotlin.test.Test
import kotlin.test.assertNotNull
import io.vertx.junit5.VertxExtension
import io.vertx.junit5.VertxTestContext
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(VertxExtension::class)
internal class AppTest {
    @Test
    fun `Run Mongo with GridFS`(vertx: Vertx, context: VertxTestContext) {
        val config = JsonObject().put("connection_string", "mongodb://localhost:55000")
        val client = MongoClient.createShared(vertx, config)
        val fs = vertx.fileSystem()

        fs.open("test.txt", OpenOptions(), context.succeeding { asyncFile ->
            client.createDefaultGridFsBucketService(context.succeeding { gridFS ->
                val options = GridFsUploadOptions()
                options.metadata = JsonObject().put("test", JsonObject().put("test", "test"))
                gridFS.uploadByFileNameWithOptions(
                    asyncFile,
                    "test.txt",
                    options, context.succeeding { result ->
                    context.verify {
                        assertNotNull(result)
                    }
                    context.completeNow()
                })
            })
        })
    }
}
